config/routes.rb
Nattogdag2::Application.routes.draw do
  resources :teams, :only => [:update, :create, :show, :new]
  resources :players, :only => [:update, :create, :show, :index]
  root :to => 'static_pages#start'
  get "static_pages/export"
  match 'export' => 'static_pages#export'
  match 'teams/:id' => 'teams#show'
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :email, :name, :team_id, :confim, :slug, :teamslug
  validates :team_id, presence: true
  belongs_to :team

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  before_validation :generate_slug

  def to_param
    slug.parameterize
  end
  def generate_slug
    self.slug ||= "#{team_id}-#{id}-#{name}".parameterize
  end

  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :email, :teamgroup, :teamname
  has_many :players, dependent: :destroy
  accepts_nested_attributes_for :players

  validates :teamgroup, presence: true, uniqueness: true
  validates :teamname, presence:   true, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :name, presence: true
  validates :slug, uniqueness: true, presence: true


  before_validation :generate_slug

  def to_param
	  slug.parameterize
	end
  def generate_slug
  self.slug ||= teamname.parameterize
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
# encoding: UTF-8
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { send_data @players.as_csv }
      format.xls # { send_data @players.to_csv(col_sep: "\t") }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find_by_slug!(params[:id].split("/").last)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find_by_slug!(params[:id].split("/").last)

  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])
    @team = Team.find_by_id(params[:team_id])

    respond_to do |format|
      if @player.save
        UserMailer.player_confirmation(@player).deliver
        format.html { redirect_to "/teams/#{@player.teamslug}", notice: 'Bra valg, men du burde nok inviter enda en!  ' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { redirect_to "/teams/#{@player.teamslug}", notice: 'Email already taken.' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find_by_slug!(params[:id].split("/").last)
    # @team = Team.find_by_slug!(params[:id].split("/").last)
    
    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to "/teams/#{@player.teamslug}", notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find_by_slug!(params[:id].split("/").last)
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def start
    
  end

	def export
		@players = Player.all
    @teams = Team.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
      format.csv { send_data @players.as_csv }
      format.xls # { send_data @players.to_csv(col_sep: "\t") }
    end
	end

end

app/controllers/teams_controller.rb
# encoding: UTF-8
class TeamsController < ApplicationController
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
      
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team = Team.find_by_slug!(params[:id].split("/").last)
    
    @confplayer = Team.find_by_slug!(params[:id].split("/").last)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find_by_slug!(params[:id].split("/").last)
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        UserMailer.signup_confirmation(@team).deliver
        format.html { redirect_to @team, notice: 'Wohoo, du får  det beste laget' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @team = Team.find_by_slug!(params[:id].split("/").last)

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
        redirect_to root_path
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team = Team.find_by_slug!(params[:id].split("/").last)
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Natt og Dag Sommerleker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <meta name="author" content="Daniel Cherubini - www.danmade.me">
  <meta property="og:title" content="NATT&amp;DAG Sommerleker"/>
  <meta property="fb:app_id" content="140777122778257">
  <meta property="og:description" content="NATT&amp;DAG og Cocio presenter Sommerleker på Sukkerbiten"/>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br />
    <%= f.number_field :team_id, :value => params[:team_id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_players.html.erb
<li>
	<span class="content"><%= player.name %></span>
</li>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.email %></td>
    <td><%= player.team_id %></td>
  </tr>
<% end %>
</table>

<br />


<p>
  Download:
  <%= link_to "CSV", players_path(format: "csv") %> |
  <%= link_to "Excel", players_path(format: "xls") %>
</p>

app/views/players/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
      </Row>
    <% @players.each do |player| %>
      <Row>
        <Cell><Data ss:Type="String"><%= player.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= player.email %></Data></Cell>
      </Row>
    <% end %>
     <% @teams.each do |team| %>
      <Row>
        <Cell><Data ss:Type="String"><%= team.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= team.email %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<div class="container">
<div class="row">
	<div class="span12">
		<div class="well text-center">
			<p id="notice"><%= notice %></p>
		  <b>Navn:</b>
		  <%= @player.name %>
			<% if @player.confim == false %>
			  <%= form_for(@player, :html => { :class => "confirm-player" }) do |u| %>
			    <%= u.hidden_field :confim, :value => "true" %>
			    <%= button_tag(type: 'submit', class: "btn btn-mini btn-info") do %>
			       <i class="icon-ok icon-white"></i> Bekrefte
			    <% end %>
			  <% end %>
			<% else %>
			  <%= form_for(@player, :html => { :class => "confirm-player" }) do |u| %>
			    <%= u.hidden_field :confim, :value => "false" %>
			    <%= button_tag(type: 'submit', class: "btn btn-mini btn-warning") do %>
			       <i class="icon-remove icon-white"></i> Meld av
			    <% end %>
			 	<% end %>
			<% end %>
		</div>
	</div>
	<div class="span12">
    <%= image_tag("cocio-logo.png", :class => "cocio-logo logo-small") %>
  </div>
  </div>
</div>

app/views/static_pages/export.html.erb
<p>
  Download:
  <%= link_to "CSV", export_path(format: "csv") %> |
  <%= link_to "Excel", export_path(format: "xls") %>
</p>

app/views/static_pages/start.html.erb
<div class="container">
	<div class="row">
		<div class="span12">
			<div class="well">
				<div class="text-center offsetback">
					<h1>Hvor jobber du da?</h1>
					<% if Team.find_by_teamgroup("db") %>
						<%= image_tag("db.jpg", :class => "big-img grey") %>
					<% else %>
						<a href="/teams/new?teamgroup=db"><%= image_tag("db.jpg", :class => "big-img") %></a>
					<% end %>

					<% if Team.find_by_teamgroup("nod") %>
						<%= image_tag("nod.jpg", :class => "big-img grey") %>
					<% else %>
						<a href="/teams/new?teamgroup=nod"><%= image_tag("nod.jpg", :class => "big-img") %></a>
					<% end %>
					
					<% if Team.find_by_teamgroup("dn") %>
						<%= image_tag("dn.jpg", :class => "big-img grey") %>
					<% else %>
						<a href="/teams/new?teamgroup=dn"><%= image_tag("dn.jpg", :class => "big-img") %></a>
					<% end %>
					
					<% if Team.find_by_teamgroup("vg") %>
						<%= image_tag("vg.jpg", :class => "big-img grey") %>
					<% else %>
						<a href="/teams/new?teamgroup=vg"><%= image_tag("vg.jpg", :class => "big-img") %></a>
					<% end %>
					
				</div>
			</div>
		</div>
	</div>
	<div class="span12">
		<%= image_tag("cocio-logo.png", :class => "cocio-logo logo-big") %>
	</div>
</div>